### ISSUE TITLE
[FEAT] Group Entity 및 API 구현

### ISSUE THREAD

**Issue by daehwan2yo** [CodingWasabi/TRTI-BE#10]
## 🤗 구현하는 기능

Group Entity 와 API 를 구성한다.

## 😳 목표 기간 

~12/28 05:00

## 😤  To-do

- [x] Entity 구성
- [x] 그룹 생성
- [x] 그룹 이미지 업로드
- [x] 그룹 정보 불러오기
- [x] 그룹 맴버들 불러오기
- [ ] 그룹 추천 조회하기

## 😋 참고사항

group
